### ISSUE TITLE
getlocal fetch takes a while

### ISSUE THREAD

**Issue by palringosteve** [BenjaminBriggs/getLocal#1]
Fetching takes a while and can look like it's not working, maybe display a friendly prompt to say it's going to take some time.

**Comment by BenjaminBriggs** [comment]
This has been addressed in the [0.0.5](https://github.com/BenjaminBriggs/getLocal/releases/tag/0.0.5) release with the introduction of the Timeout (-t) option on the fetch command. You can now specify your own time out instead of the default 600 seconds.
